### ISSUE TITLE
Several Issues and Needing help

### ISSUE THREAD

**Issue by MelodyofSound** [PerfectRaito/StarboundSimpleVoreMod#228]
Cant teleport to the food hall even though Ive deleted the temp data and the removed npc that broke the hall
Cant get any tenants to spawn in (nothing has explained it well about the tags id use the badges but cant spawn those in)
Could only spawn in the portable bellybound shop

**Comment by Lovis07** [comment]
How do you fix it?

**Comment by MelodyofSound** [comment]
Basically removed the npc and what ever else I forgot to remove the { in one line of code and thats what was breaking it and so when it was removed the issue resolved
