### ISSUE TITLE
Vore Mall Teleportation

### ISSUE THREAD

**Issue by GlorifiedSpaceDragon** [PerfectRaito/StarboundSimpleVoreMod#238]
For some reason in the 9.5.0A version of this mod, whenever I try to teleport to the Food Hall, it just warps me straight back to the outpost again. I'm not sure what the heck I'm doing wrong, but I did everything right and yet the mod is acting strange like that. Not sure what to do exactly in this situation.

**Comment by Jiraius** [comment]
What did you do to fix it?

**Comment by GlorifiedSpaceDragon** [comment]
I forgot exactly how I did it. It’s been quite a while since I played Starbound lol. Been busy doing other things or playing other games. But I know I did fix it though.On Sep 29, 2024, at 6:10 AM, Jiraius ***@***.***> wrote:﻿
What did you do to fix it?
