### ISSUE TITLE
Shark?

### ISSUE THREAD

**Issue by IratuElexion** [PerfectRaito/StarboundSimpleVoreMod#28]
So, I can't seem to get the shark (or any of the taurs/zebras/unicorn)... but mainly the shark. Built a house made of sandstone, sand floor and background, and filled it with water. Put a shark tank on the floor, a oil lamp on the back, a door, then put up the tenant thing... and fox. The hell?

**Comment by Sheights** [comment]
To summon the shark, you need 24 blocks worth of 'sea' tiles. Each piece of 'sea' furniture is worth 'sea' tiles equal to the amount of space it takes up.
