### ISSUE TITLE
RubySnoot

### ISSUE THREAD

**Issue by TershaSerouDreemurr** [PerfectRaito/StarboundSimpleVoreMod#32]
rubysnoot sometimes causes my game to crash because an idle action fails to load.

**Comment by PerfectRaito** [comment]
Could you provide us some crash logs or such from when this happens, error messages that you get, etc?

**Comment by TershaSerouDreemurr** [comment]
It hasn't been happening lately, so it's hard to give a crash log, though I did notice something else. The newer tenant races die whenever you call them through the colony deed.

**Comment by TershaSerouDreemurr** [comment]
Aha! (Fatal Exception caught: (AssetException) Error loading asset/objects/vore/ruby/rubysnoot.png:yawn.1

**Comment by PerfectRaito** [comment]
Could you possibly give me the entire log pasted into someplace like pastebin or such?
I'll work out from the assumption that you have completly deleted the mod, and unpacked the new updated one, and not just pasted it over the old folder.
Else, i'll see what i can find based from this. The line would suggest there was a problem loading that asset.

**Comment by TershaSerouDreemurr** [comment]
I didn't get any crash report or log, that was the full error message that popped up when it crashed. And yes, I removed the old folder before pasting the new one.

**Comment by PerfectRaito** [comment]
Weird. I just tried it on my end and it loaded perfectly fine for me. Did you try reinstalling the mod?

**Comment by TershaSerouDreemurr** [comment]
It works for a while but after a certain amount of time off-screen but in the same world, it'll crash with that error message.

**Comment by PerfectRaito** [comment]
Check your " \Steam\steamapps\common\Starbound\giraffe_storage " folder and see if you can give us the " starbound.txt " file, or " starbound.1 ", 2 or such. Neither Sheights or i can seem to reproduce this bug.

Do you happen to have any other mods installed, and what version of Starbound are you running?

**Comment by TershaSerouDreemurr** [comment]
the starbound.log.1 , 2 ,etc? And yes I have other mods installed, mainly race mods
And I'm using Glad Giraffe - Update 1 (December 8, 2015)

**Comment by PerfectRaito** [comment]
Yes, those would be nice, prefereably after you had the crash happen so it's fresh in the logs.

Paste them here: http://pastebin.com/ and send us the link here, and i'll have a look at it. This is a strange thing,

**Comment by TershaSerouDreemurr** [comment]
if I haven't played it since the latest crash, is that alright?

**Comment by PerfectRaito** [comment]
That will do nicely. Please report back with the logs as soon as possible.

**Comment by TershaSerouDreemurr** [comment]
Actually, do I paste the latest updated log?
I have 5 starbound.log that were updated at the same time with another starbound.log that was the latest updated.

**Comment by PerfectRaito** [comment]
If you haven't played since last time you crashed, the latest one will do fine.
The starbound.log should be the most recent, while starbound.1.log and out is subsiquent logs.

**Comment by TershaSerouDreemurr** [comment]
Okay.

**Comment by TershaSerouDreemurr** [comment]
http://pastebin.com/iFQbUW9A

**Comment by PerfectRaito** [comment]
Looking into the log file you provided i see alot of weird information. Errors relating to guards which i am told might have to do with how they are scripted by the game devs and problems with audio files. In the end, you're getting a "std::exception: bad allocation" error, which seems like a memory problem.

Do you got any guards in your ship or world? Try removing them. If the problem still persists, feel free to make another post here. Make sure to bring another log then.

**Comment by TershaSerouDreemurr** [comment]
I have absolutely no guards...

**Comment by PerfectRaito** [comment]
I can also see some problems loading your "Kangaru.modpak" file. Might want to look into either updating it or removing it, unless it works fine on your end. I'd also recommend you try reinstalling SSVM by removing all files and download a fresh set from 7.1.0. Might fix some of the problems.

**Comment by TershaSerouDreemurr** [comment]
Okay, thanks.

**Comment by TershaSerouDreemurr** [comment]
Everything's been working fine now. I'm assuming something corrupted during the installation of SSVM for me - and the Kangaru mod is alright now.
