### ISSUE TITLE
Nom animation

### ISSUE THREAD

**Issue by IroRaze** [PerfectRaito/StarboundSimpleVoreMod#42]
Ther is a nom animation but i dont get inside the pred

**Comment by PerfectRaito** [comment]
Have you tried reinstalling the mod? Alot of problems can be solved this way. When you install a new version of the mod, you have to make sure you delete the older version folder completly before you paste in the new one.

If that does not help, you could send more information, like this:

What predator does this happen to, if not all?
SPO's or Tenants?
Could you provide us with the log from the session this happened to?
 (...\Steam\steamapps\common\Starbound\giraffe_storage - the starbound.log file. Paste it into pastebin.com and post the link to it here)

This will help us narrow down the problem. Thanks!

**Comment by IroRaze** [comment]
reinstalling doesn'T help at all.
i figured out that it's don'T work with all races. only with humane race it works for me.
And it's only don't work with the Tenant.
here is the log from the last session:
http://pastebin.com/TsNyDum4

Sorry for my bad english, and thanks for the help!

**Comment by PerfectRaito** [comment]
Try turning your admin mode off before you try to enter the tenants or the SPO's. Did that help?

**Comment by IroRaze** [comment]
And now i feel like a complet Idiot...

that helped...

**Comment by PerfectRaito** [comment]
Just glad it worked out for you. Next time try reading up a bit, checking the wiki and the forum if you can find the solution to your problem next time.

Case closed.
